version: '3.8'

services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mypass
      MARIADB_DATABASE: catty_reminders
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    restart: always
    ports:
      - "0.0.0.0:8181:8181/tcp"
    environment:
      - DEPLOY_REF=${IMAGE_TAG}
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mypass
      - DB_NAME=catty_reminders
    depends_on:
      - db

volumes:
  db_data: