services:
  catty-app:
    image: ${APP_IMAGE}
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    environment:
      - DEPLOY_REF=${DEPLOY_REF}
    ports: 
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./config.json:/catty-reminders-app/config.json:ro
    depends_on:
      - db
    networks:
      - catty-network
  
  db:
    image: mysql:latest
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - catty-network

networks:
  catty-network:
    driver: bridge

volumes:
  db_data: